# Generated by Django 5.0.5 on 2024-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofileinformation_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscordaccountinformation',
            name='token_expiry',
            field=models.IntegerField(default=0),
        ),
    ]
