# Generated by Django 5.0.5 on 2024-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userdiscordaccountinformation_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscordaccountinformation',
            name='discord_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
