# Generated by Django 5.0.5 on 2024-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userdiscordaccountinformation_discord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscordaccountinformation',
            name='token_expiry',
            field=models.DateTimeField(),
        ),
    ]
