# Generated by Django 5.0.5 on 2024-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_alter_userdiscordaccountinformation_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinformation',
            name='user',
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('discord_user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_expiry', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(upload_to='media/profile_pics/')),
                ('is_police', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='registereduser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='registereduser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserDiscordAccountInformation',
        ),
        migrations.DeleteModel(
            name='UserProfileInformation',
        ),
    ]
