# Generated by Django 5.0.5 on 2024-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userprofileinformation_user_registereduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
